# Generated by Django 4.1 on 2022-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('numdos', models.CharField(db_index=True, max_length=10)),
                ('numdosverling', models.CharField(max_length=10)),
                ('ancart', models.CharField(max_length=20)),
                ('filiere', models.CharField(max_length=5)),
                ('etape', models.FloatField()),
                ('verling', models.CharField(max_length=8)),
                (
                    'file_format',
                    models.CharField(
                        choices=[
                            ('COUV_JPEG_BQ', 'Couv Jpeg Bq'),
                            ('COUV_JPEG_HQ', 'Couv Jpeg Hq'),
                            ('PDF_POD', 'Pdf Pod'),
                            ('PDFC', 'Pdfc'),
                            ('PDFI', 'Pdfi'),
                            ('PDFRL', 'Pdfrl'),
                            ('XML', 'Xml'),
                            ('XMLRL', 'Xmlrl'),
                            ('', 'No Format'),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
